### PR TITLE
Change var to const in the function definitions

### PR DESCRIPTION
**Pull request by GypsyDangerous**

### CODE REVIEW

**Comment by nastyox** [comment]
Thanks for the contribution! I'm accepting your suggestion, but it will be kept on the task list for a later date because "const" causes a syntax error in IE 10. While that browser and version may already seem quite outdated to forward-thinking (or even present-thinking) coders, I don't ever want Rando.js to put a stick in the spokes of someone's project that's trying to serve past-thinking users. Again, thank you very much for taking an interest in the project- especially enough to create a pull request.

**Comment by GypsyDangerous** [comment]
What do you think about using something like babel, that way you can use modern things like const but it will transpile it to a version that can be run on any browser

**Comment by nastyox** [comment]
I really want to keep Rando.js as unobtrusive and clear-cut as possible, so I don't want to bundle anything in with the project to make it not only larger, but also dependent. If I were to use Babel with this project at all, I'd just run the Rando.js code through [Babel's online tool](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAJwIZgCZwBSuQcwEYAaRPfAJlPIGYBKAbwChFXEA3PRGAZwFVMAU2AwwgjIgC8ibJ2QxUAIwA2gulIB8iKAE8ADoLjAOeBSsFTJ0gETgMw0eOvEWbXgDkQAW0WDkUmTBvdUktXQMjRCCvSxto32RrRAAyZMQAQg9Ud2xouhc2bh4AZSh5MHwA7B4ykLD9Q2Ma_ysbZtF8Z1dWXgB5RQArQWgquEG67QbIsYHYxGsZ4aguwt4AQWQ0HSq8ZAnM_iERMQxcTfVUsk2MqyiQZWUUtN2AOggEZpBoOBbbja2CmwIMh9FA4AAldBYGLSbATZiFQplHQIxFouSIYGgiFQuBeHikLF6MGQzB44rKGAQQQ8AIAbQAuoSQcScWSvABubpotgAdwAFjBVNhsESSbiYfMXkkANSYlni9kUqk0l4DOCibDWax0OgvVQVKD8xAAHkQNAADIxuTzEWK2dDabDeaIsLy3gq4IgAD7exAusnu_EAYU9evwgigpOhADVUMoQDTcoJeYg-KIoDQKP9UDpsABWXVc2224A_WRcGABC0c7im-XY6N4nj6wSG_m1mAymXWkt9kz-e1NrzK6kBIcSnh0mAMl5g0rlfBwl48SnU7AkRAAWkIdGL_dtMGAos9w9Hglb7cQWitDdZZ7XNLpE6Vj5bBvwRoZ49PEvP-4PVgAF8bR5ECD2QSMQGQJBPB8PwT0bCU91A4DUMxVAoAgflsDUVE-0gqBoKQABZTD-ReNB2ThADEXAtggNo7lkXwxEjzOIgbmkIIHieK5KC4u5eMuWhBJ45Re37djeAEexjnEDjd0kwDEAAelUyD8HuLh7AgGAvHjdDbUI4i70VaEaKMhirNYGzuGPdJ0gDN01QARUTEE-PIQhuDAGp0GpSIBncvxtkuGSjkcU5yAoXVWIPdTgo87ZFmgOzVmPbzL0_Y1blvEyYMQYB4x4QRaIPDFXUEAAPAIqKwbALWoAhCGyo1t0QXdyv7AqkAYKrqoALgG0hOATQRBqywQAEdsAGuhGLs-i-zs6SeDghJFIuNIPG8TaYu2ooFw6Dj6C8ggaDnOAABk4F5Pxg1QUrlzKfS4UseZgGUOBMJ1eL-3Ur6fqgIrkDxRAvFEbQvQM2q5sgBMeBgdgLEiSGkChRAaogRHkdR4xYbodK3Eylrr342KB20QQvD0AIYuagTpG8xmfOkKAab0bqCKgwqXws9QACoZBijrvPUOVvO5ui7NW491k2XMtvOog2uNG8-IiuSoo42LlMA9TdlzYnWAxXZ6Za0g9CpABrcQAEkhFq6R-bxd7hdeD92pNM0axNlBeb6gbBsQa2IDtjBHfsarRvjRMQ92Okw4jqOaoZRaD2Wks5bmnh-iGaBlfCw5tZOXW4v99TUqgf2MRmC2iFIO2dCdRB86WF5m54bAZhQlSemPLu1fJq1_pUjFm4CLu6SHr3jWF12vHen3EAtBlpYgwPEAYZuQ-b2PxpDmYZ8EHR043sCltlg92JFby5jKRMVYoOZiuUUr1F9EWydaIqSosESBAX6_0fmoQ6WsHBl1oBXfualVKKDgHAVQ6B_a9RQLiZeiAXj5gvmhA8OddrwWQEXHaJdIEKQOvrBKqkMyg3BhabQ_IwYgHwMaWGbdwQQyhkaZhrDV72SiIIfAmE8YyFEDjEASMUaIEiAg9q6MyCYAhqgaqRNYHsXvhoaQ-Ut71RwE1fiXVUG6IwSzVefd-xZ1tAQ9ae0ELi01iUV6FRy7Pyurde6yBHrPT1K9JeIQbBA1-o42S5DooXRgf3QG31MJ0JiAwsEyjaq9E4QoxJDCjyCOEbAaR8MJFSPxlwjGSjsa42kWjFRaj-5oM0doxAAB-dBZJGqs1INYIJyx1Ahz0YpUgBj2kxM6bgxAVieQ2I2vYlq4DbFENccXUJ8lwn4HoFQgGNCwAg2AGDGIaSmFwBYWwlRYiEaSNEbIuA8ioaY0Jv7DRZMtAHSphzWmDcqAUwbpue-7NObDMKF8xAZEjQvCBuWcWjNgEAvIsC76oKgEWJUmgwFFEQXEMXu7b-AktyGMQHKXcOLDHwpLKMtENjjouIcYA1Wc8R4hMilAuFqy-zqXaBUYxRFCpZWwngNYUBsA9IMVlalWKlLDOJSM9CaC36lVolnCAmFsK4UZQHdlSApVlW5CBECTBQCQFgAgJpWBigzUTJAQQvSKb60qmQxZVQ5BmFUBMcIjQBz2osL_WwdKnCAh6DMhIVQ8iaEmBEYw0Q5jWHiH4JIlwDjuGyLkYI3qjrOMqLCZojqphNDKGGllnRE19EGEsUY4xA1OumIMMN1cVhuB4DmbYsJdj7AgYss4exzr-HSLccSba3gfEft8X40ha1MSRCCMe9lc4LJ1g4r-XzO33EeDOoBcxxLqElf_Dk6lRBjRgBIcg3g2xQB4OhdCZtrjSEZNLdC7FHLOTum5ZKKsfKiH8qaoKIVPLzM9UsvWY7CiJXfSlAtaUb6kypW2HKI8lW2nNtIPRRrpomvXAKlqw9hWEoPGWYhlVqydnrJ7cDRpOzdnUInGcAR-pO0mpsacTITCHymrNUjDIFqirsjUzY0sxVXock2qdDLf0k2wDGuxxDp1-mE7Mx5i7OIAFJOo0uky_OTPkbyrq3mqjd6zt27oIPujZR78HUNoVs8GuzeGHLhuIsphS5FsKuUom5IHFLk0eRiZ5dNmZAPBR81mAR3PDMwxWfwVZPNEFwyaULFAiM9iuMgOk-H2zfmkDATj6FBDvwsGtWtJCiiTvpZQSJTLVJGx0HZQL2HtHhcMWraLJHqMJZykl7ewcYAH3jt5GjGdL62nS6Vcd-aC68opaQvLFD-N2SrkBmuGHywYj0GDOmVypnjvbtAF482LkXIaC8fkT1ei8jAAABQW34XQbx4zKHNRtvQupYvxc2GrJrO9T6DWu21iaHXrvn3QmK3rmX5ZOMXDl3j-Wf0TdUjmsrs3Kw4brGaQVBGOzcGI3dhrX4PlvF28gHlc10PWR6xl_rvrJlEGmaN79hWSybo2XE_hPD9l8PYSkopjDzP8MyWIbJoi8nWZkcYWzLPrmVLY1vWp_DGlweNW2JDrMukGrgPBxDZqzFWlSwT0qAnWDU-0_xPTh6Rcqr_hltXYzbTMv5CAYAX0LBjUTAZnklUnYABUFe8lQHoAA6jAQj6FAshdi6hzquGbydi3FudQA0XfFDd5773uV5e49IO5i2cWZzNVT010jzvXfu691-dP05s_R9z3Hpr_nj3GVFxxjV3I5VYRwnhCV6n1016AkAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Cenv&prettier=true&targets=&version=7.11.6&externalPlugins=) and use that raw code as the project's source code. The problem with `const` there is that...

Running this code through Babel:
```JavaScript
const a = 1;
a = 2;
console.log(a);
```

Produces this result:
```JavaScript
"use strict";

function _readOnlyError(name) {
  throw new Error('"' + name + '" is read-only');
}

var a = 1;
a = (_readOnlyError("a"), 2);
console.log(a);
```

So it seems Babel chooses to use `var` instead of `const` as well. Given that fact, I think Rando.js' current code satisfies both developer-friendliness and user-robustness well, but if you can break it with an old or weird browser, I would be more than happy to address that.

Also, please note that the code is completely released into the public domain, so you should feel free to copy and alter it any way you choose for any purpose you choose.

Thanks for following up with this and seeking to make the project the best it can be!

**Comment by GypsyDangerous** [comment]
babel uses var so it can run on legacy browsers. There is nothing inherently wrong with var but it is easier to with let and const because of the way they act. Babel can use var because it know how to correctly convert let/const into var. the concept of Read only variables is there for the developer so we don't accidentally change something we shouldn't. When running the code the fact that the variable is read only won't change anything unless you try to change it. That is why babel throws the read only error.

using const wouldn't change the user experience (unless they are on an old browser (which is why we use babel to convert const to var so it will work on old browsers)), It will only make it more developer friendly and less prone to bugs.

regarding the size of the package when using babel, it doesn't make it that much bigger. I have a few packages made in typescript (which is transpiled in a similar way) and they are not much bigger than rando.js

I understand if you don't want to change it just giving my two cents :)

**Comment by f478ccf2** [comment]
Why use `var` when you're already using arrow functions? They were only introduced with ES6, which also introduces let and const.

**Pull request closed without merging**
